package rentalmobil;

/**
 *
 * @author M S I
 */
public class frmMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public frmMenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnBar = new javax.swing.JMenuBar();
        mnPegawai = new javax.swing.JMenu();
        mnDataPegawai = new javax.swing.JMenuItem();
        mnCustomer = new javax.swing.JMenu();
        mnDataCustomer = new javax.swing.JMenuItem();
        mbMobil = new javax.swing.JMenu();
        mnDataMobil = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenu();
        mnPeminjaman = new javax.swing.JMenuItem();
        mnPengembalian = new javax.swing.JMenuItem();
        mnLaporan = new javax.swing.JMenu();
        mnLaporanPeminjaman = new javax.swing.JMenuItem();
        mnLaporanPengembalian = new javax.swing.JMenuItem();
        ReportPegawai = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnAbout = new javax.swing.JMenu();
        mnTentang = new javax.swing.JMenuItem();
        mnPembuat = new javax.swing.JMenuItem();
        mnManualBook = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenu();
        mnLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");

        mnPegawai.setText("Pegawai");
        mnPegawai.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        mnDataPegawai.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mnDataPegawai.setText("Data Pegawai");
        mnDataPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDataPegawaiActionPerformed(evt);
            }
        });
        mnPegawai.add(mnDataPegawai);

        mnBar.add(mnPegawai);

        mnCustomer.setText("Customer");
        mnCustomer.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        mnDataCustomer.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mnDataCustomer.setText("Data Customer");
        mnDataCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDataCustomerActionPerformed(evt);
            }
        });
        mnCustomer.add(mnDataCustomer);

        mnBar.add(mnCustomer);

        mbMobil.setText("Mobil");
        mbMobil.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        mnDataMobil.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mnDataMobil.setText("Data Mobil");
        mnDataMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDataMobilActionPerformed(evt);
            }
        });
        mbMobil.add(mnDataMobil);

        mnBar.add(mbMobil);

        mnTransaksi.setText("Transaksi");
        mnTransaksi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        mnPeminjaman.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mnPeminjaman.setText("Peminjaman");
        mnPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPeminjamanActionPerformed(evt);
            }
        });
        mnTransaksi.add(mnPeminjaman);

        mnPengembalian.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mnPengembalian.setText("Pengembalian");
        mnPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPengembalianActionPerformed(evt);
            }
        });
        mnTransaksi.add(mnPengembalian);

        mnBar.add(mnTransaksi);

        mnLaporan.setText("Laporan");
        mnLaporan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        mnLaporanPeminjaman.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mnLaporanPeminjaman.setText("Laporan Peminjaman");
        mnLaporanPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanPeminjamanActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLaporanPeminjaman);

        mnLaporanPengembalian.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mnLaporanPengembalian.setText("Laporan Pengembalian");
        mnLaporanPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanPengembalianActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLaporanPengembalian);

        ReportPegawai.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ReportPegawai.setText("Daftar Pegawai");
        ReportPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportPegawaiActionPerformed(evt);
            }
        });
        mnLaporan.add(ReportPegawai);

        jMenuItem1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jMenuItem1.setText("Daftar Customer");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnLaporan.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jMenuItem2.setText("Daftar Mobil");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnLaporan.add(jMenuItem2);

        mnBar.add(mnLaporan);

        mnAbout.setText("About");
        mnAbout.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        mnTentang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mnTentang.setText("Tentang");
        mnTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTentangActionPerformed(evt);
            }
        });
        mnAbout.add(mnTentang);

        mnPembuat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mnPembuat.setText("Pembuat");
        mnPembuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPembuatActionPerformed(evt);
            }
        });
        mnAbout.add(mnPembuat);

        mnManualBook.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mnManualBook.setText("Manual book");
        mnManualBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnManualBookActionPerformed(evt);
            }
        });
        mnAbout.add(mnManualBook);

        mnBar.add(mnAbout);

        mnKeluar.setText("Keluar");
        mnKeluar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        mnLogOut.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        mnLogOut.setText("Log Out");
        mnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogOutActionPerformed(evt);
            }
        });
        mnKeluar.add(mnLogOut);

        mnBar.add(mnKeluar);

        setJMenuBar(mnBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPeminjamanActionPerformed
        FrTransaksi FT = new FrTransaksi();
        FT.setVisible(true);
    }//GEN-LAST:event_mnPeminjamanActionPerformed

    private void mnManualBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnManualBookActionPerformed
        frmManualBook mb = new frmManualBook();
        mb.setVisible(true);
    }//GEN-LAST:event_mnManualBookActionPerformed

    private void mnDataPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDataPegawaiActionPerformed
        frmDataPegawai dp = new frmDataPegawai();
        dp.setVisible(true);
    }//GEN-LAST:event_mnDataPegawaiActionPerformed

    private void mnDataCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDataCustomerActionPerformed
        frmDataCustomer dc = new frmDataCustomer();
        dc.setVisible(true);
    }//GEN-LAST:event_mnDataCustomerActionPerformed

    private void mnDataMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDataMobilActionPerformed
        frmDataMobil dm = new frmDataMobil();
        dm.setVisible(true);
    }//GEN-LAST:event_mnDataMobilActionPerformed

    private void mnPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPengembalianActionPerformed
        FrPengembalian FP = new FrPengembalian();
        FP.setVisible(true);
    }//GEN-LAST:event_mnPengembalianActionPerformed

    private void mnLaporanPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanPeminjamanActionPerformed
        frmLaporanPeminjaman lpj = new frmLaporanPeminjaman();
        lpj.setVisible(true);
    }//GEN-LAST:event_mnLaporanPeminjamanActionPerformed

    private void mnLaporanPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanPengembalianActionPerformed
        frmLaporanPengembalian lpb = new frmLaporanPengembalian();
        lpb.setVisible(true);
    }//GEN-LAST:event_mnLaporanPengembalianActionPerformed

    private void mnTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTentangActionPerformed
        frmTentang tt = new frmTentang();
        tt.setVisible(true);
    }//GEN-LAST:event_mnTentangActionPerformed

    private void mnPembuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPembuatActionPerformed
        frmPembuat pb = new frmPembuat();
        pb.setVisible(true);
    }//GEN-LAST:event_mnPembuatActionPerformed

    private void mnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogOutActionPerformed
        frmLogin lg = new frmLogin();
        lg.setVisible(true);
    }//GEN-LAST:event_mnLogOutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frmDaftarCust Dcus = new frmDaftarCust();
        Dcus.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ReportPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportPegawaiActionPerformed
        frmDaftarPegawai dafPeg = new frmDaftarPegawai();
        dafPeg.setVisible(true);
    }//GEN-LAST:event_ReportPegawaiActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        frmDaftarMobil DaMob = new frmDaftarMobil();
        DaMob.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ReportPegawai;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu mbMobil;
    private javax.swing.JMenu mnAbout;
    private javax.swing.JMenuBar mnBar;
    private javax.swing.JMenu mnCustomer;
    private javax.swing.JMenuItem mnDataCustomer;
    private javax.swing.JMenuItem mnDataMobil;
    private javax.swing.JMenuItem mnDataPegawai;
    private javax.swing.JMenu mnKeluar;
    private javax.swing.JMenu mnLaporan;
    private javax.swing.JMenuItem mnLaporanPeminjaman;
    private javax.swing.JMenuItem mnLaporanPengembalian;
    private javax.swing.JMenuItem mnLogOut;
    private javax.swing.JMenuItem mnManualBook;
    private javax.swing.JMenu mnPegawai;
    private javax.swing.JMenuItem mnPembuat;
    private javax.swing.JMenuItem mnPeminjaman;
    private javax.swing.JMenuItem mnPengembalian;
    private javax.swing.JMenuItem mnTentang;
    private javax.swing.JMenu mnTransaksi;
    // End of variables declaration//GEN-END:variables
}
